/**
 * Hand-written to match supabase/schema.sql.
 *
 * Not generated by the Supabase CLI on purpose — generation needs a CLI login
 * and a network round trip, and the schema is small enough that keeping these
 * in sync by hand is cheaper. If you change schema.sql, change this too.
 */

export type LguType = 'city' | 'municipality' | 'barangay'
export type OfficerRole = 'officer' | 'reviewer'
export type ServiceStatus = 'draft' | 'flagged' | 'published' | 'rejected'
export type FlagSeverity = 'info' | 'warn' | 'block'
export type RequestStatus = 'submitted' | 'approved' | 'rejected' | 'issued'
export type FeeStatus = 'unpaid' | 'waived' | 'paid'

/** A single field in a citizen-facing form, stored in lgu_services.form_fields. */
export type FormField = {
  key: string
  label: string
  type: 'text' | 'number' | 'date' | 'select' | 'textarea'
  required: boolean
  options?: string[]
  /** 'everify' means we prefill this from verified identity data, not ask for it. */
  source?: 'everify'
}

export type Waiver = {
  category: string
  label: string
  waives: 'full' | 'partial'
  amount?: number
}

export type Eligibility = {
  min_residency_years?: number
  min_age?: number
  max_monthly_income?: number
}

export type AllowedRules = {
  fee_range?: [number, number]
  waiver_categories?: string[]
  eligibility_keys?: string[]
  max_custom_fields?: number
}

export type Lgu = {
  id: string
  name: string
  type: LguType
  parent_id: string | null
  region: string | null
  psgc_code: string | null
  letterhead_url: string | null
  seal_url: string | null
  created_at: string
}

export type Officer = {
  id: string
  egov_sub: string
  lgu_id: string | null
  full_name: string
  position: string | null
  role: OfficerRole
  created_at: string
}

export type ServiceTemplate = {
  id: string
  code: string
  name: string
  description: string | null
  base_fields: FormField[]
  allowed_rules: AllowedRules
  max_fee: number | null
  created_at: string
}

export type LguService = {
  id: string
  lgu_id: string
  template_id: string
  status: ServiceStatus
  fee_amount: number
  waivers: Waiver[]
  required_docs: string[]
  eligibility: Eligibility
  form_fields: FormField[]
  doc_template_path: string | null
  submitted_at: string | null
  published_at: string | null
  created_at: string
}

export type ValidationFlag = {
  id: string
  lgu_service_id: string
  rule_code: string
  severity: FlagSeverity
  message: string
  field_path: string | null
  resolved: boolean
  created_at: string
}

export type ServiceRequest = {
  id: string
  lgu_service_id: string
  citizen_sub: string | null
  citizen_name: string | null
  citizen_mobile: string | null
  everify_payload: Record<string, unknown> | null
  liveness_session: string | null
  liveness_passed: boolean
  form_data: Record<string, unknown>
  status: RequestStatus
  fee_due: number
  fee_status: FeeStatus
  waiver_applied: string | null
  payment_ref: string | null
  control_number: string | null
  pdf_path: string | null
  doc_hash: string | null
  chain_tx: string | null
  issued_at: string | null
  created_at: string
}

export type RequestEvent = {
  id: string
  request_id: string
  actor: string
  event: string
  payload: Record<string, unknown>
  created_at: string
}

/** Rows are Insert-able with generated columns omitted. */
type Insertable<T> = Omit<T, 'id' | 'created_at'> & { id?: string; created_at?: string }

export type Database = {
  public: {
    Tables: {
      lgus: { Row: Lgu; Insert: Insertable<Lgu>; Update: Partial<Lgu> }
      officers: { Row: Officer; Insert: Insertable<Officer>; Update: Partial<Officer> }
      service_templates: {
        Row: ServiceTemplate
        Insert: Insertable<ServiceTemplate>
        Update: Partial<ServiceTemplate>
      }
      lgu_services: {
        Row: LguService
        Insert: Insertable<LguService>
        Update: Partial<LguService>
      }
      validation_flags: {
        Row: ValidationFlag
        Insert: Insertable<ValidationFlag>
        Update: Partial<ValidationFlag>
      }
      requests: {
        Row: ServiceRequest
        Insert: Insertable<ServiceRequest>
        Update: Partial<ServiceRequest>
      }
      request_events: {
        Row: RequestEvent
        Insert: Insertable<RequestEvent>
        Update: Partial<RequestEvent>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
