/**
 * Hand-written to match supabase/schema.sql.
 *
 * Not generated by the Supabase CLI on purpose — generation needs a CLI login
 * and a network round trip, and the schema is small enough that keeping these
 * in sync by hand is cheaper. If you change schema.sql, change this too.
 */

export type LguType = 'city' | 'municipality' | 'barangay'
export type OfficerRole = 'officer' | 'reviewer'
export type ServiceStatus = 'draft' | 'flagged' | 'published' | 'rejected'
export type FlagSeverity = 'info' | 'warn' | 'block'
export type RequestStatus = 'draft' | 'submitted' | 'approved' | 'rejected' | 'issued'
export type FeeStatus = 'unpaid' | 'waived' | 'paid'
export type ProviderSource = 'live' | 'mock' | 'fallback'
export type IssuanceStatus = 'not_started' | 'processing' | 'failed' | 'issued'
export type SmsStatus = 'not_sent' | 'sending' | 'sent' | 'failed' | 'unknown'

/** A single field in a citizen-facing form, stored in lgu_services.form_fields. */
export type FormField = {
  key: string
  label: string
  type: 'text' | 'number' | 'date' | 'select' | 'textarea'
  required: boolean
  options?: string[]
  /** 'everify' means we prefill this from verified identity data, not ask for it. */
  source?: 'everify'
}

export type UploadedDocument = {
  path: string
  requirement: string
  filename: string
  mimeType: 'image/jpeg' | 'image/png' | 'application/pdf'
  size: number
}

export type Waiver = {
  category: string
  label: string
  waives: 'full' | 'partial'
  amount?: number
}

export type Eligibility = {
  min_residency_years?: number
  min_age?: number
  max_monthly_income?: number
}

export type AllowedRules = {
  fee_range?: [number, number]
  waiver_categories?: string[]
  eligibility_keys?: string[]
  max_custom_fields?: number
  typical_min_residency_years?: number
}

export type Lgu = {
  id: string
  name: string
  type: LguType
  parent_id: string | null
  region: string | null
  psgc_code: string | null
  letterhead_url: string | null
  seal_url: string | null
  official_email: string | null
  registered_by: string | null
  registered_at: string | null
  logo_url: string | null
  created_at: string
}

/** PSA geographic reference — backs the "Register LGU" lookup. */
export type PsgcEntry = {
  code: string
  name: string
  level: 'region' | 'province' | 'municipality' | 'city' | 'barangay'
  parent_code: string | null
  region_code: string | null
  province_code: string | null
}

export type Officer = {
  id: string
  egov_sub: string | null
  lgu_id: string | null
  full_name: string
  position: string | null
  office: string | null
  role: OfficerRole
  /** Server-managed eGovPH identity binding fields; never browser editable. */
  sso_email: string | null
  sso_birthdate: string | null
  created_at: string
}

/** A profile supplied by eGovPH and refreshed only at successful SSO login. */
export type EgovIdentity = {
  id: string
  egov_sub: string
  full_name: string
  first_name: string
  middle_name: string
  last_name: string
  suffix: string | null
  birthdate: string | null
  address: string | null
  email: string | null
  mobile: string | null
  source: ProviderSource
  created_at: string
  updated_at: string
}

export type ServiceTemplate = {
  id: string
  code: string
  name: string
  description: string | null
  base_fields: FormField[]
  allowed_rules: AllowedRules
  max_fee: number | null
  created_at: string
}

export type LguService = {
  id: string
  lgu_id: string
  template_id: string
  status: ServiceStatus
  fee_amount: number
  waivers: Waiver[]
  required_docs: string[]
  eligibility: Eligibility
  form_fields: FormField[]
  doc_template_path: string | null
  /** The natural-language prompt an officer typed, when generated_by === 'ai'. */
  source_prompt: string | null
  generated_by: 'ai' | 'upload' | 'manual' | null
  generator_model: string | null
  /** Which office signs off, e.g. 'Municipal Health Office'. */
  approval_office: string | null
  generation_confidence: number | null
  reviewed_by: string | null
  reviewed_at: string | null
  submitted_at: string | null
  published_at: string | null
  created_at: string
}

export type ValidationFlag = {
  id: string
  lgu_service_id: string
  rule_code: string
  severity: FlagSeverity
  message: string
  field_path: string | null
  resolved: boolean
  resolution_note: string | null
  resolved_by: string | null
  resolved_at: string | null
  created_at: string
}

export type StudioGenerationCache = {
  id: string
  lgu_id: string
  input_kind: 'prompt' | 'extraction'
  input_hash: string
  result: unknown
  engine: 'egov-ai' | 'openai' | 'mock'
  model: string
  source: 'live' | 'mock' | 'fallback'
  primary_error: string | null
  created_at: string
  updated_at: string
}

export type ServiceRequest = {
  id: string
  lgu_service_id: string
  citizen_sub: string | null
  citizen_name: string | null
  citizen_mobile: string | null
  everify_payload: Record<string, unknown> | null
  liveness_session: string | null
  liveness_passed: boolean
  form_data: Record<string, unknown>
  status: RequestStatus
  fee_due: number
  fee_status: FeeStatus
  waiver_applied: string | null
  payment_ref: string | null
  payment_uuid: string | null
  payment_url: string | null
  payment_txnid: string | null
  payment_source: ProviderSource | null
  payment_checked_at: string | null
  uploaded_docs: UploadedDocument[]
  /** Liveness confidence out of 100. We accept only >= 95.0. */
  liveness_score: number | null
  everify_reference: string | null
  approved_by: string | null
  approved_at: string | null
  rejected_by: string | null
  rejected_at: string | null
  rejection_note: string | null
  issuance_status: IssuanceStatus
  issuance_attempts: number
  issuance_started_at: string | null
  issuance_error: string | null
  control_number: string | null
  pdf_path: string | null
  doc_hash: string | null
  chain_tx: string | null
  chain_block_number: number | null
  chain_anchored_at: string | null
  chain_source: ProviderSource | null
  sms_status: SmsStatus
  sms_source: ProviderSource | null
  sms_message_id: string | null
  sms_sent_at: string | null
  sms_error: string | null
  issued_at: string | null
  created_at: string
}

export type RequestEvent = {
  id: string
  request_id: string
  actor: string
  event: string
  payload: Record<string, unknown>
  created_at: string
}

/**
 * Rows are Insert-able with generated columns omitted, and every column that
 * has a DB-side default becomes optional.
 */
type Insertable<T, Optional extends keyof T = never> = Omit<T, 'id' | 'created_at' | Optional> &
  Partial<Pick<T, Optional>> & { id?: string; created_at?: string }

/**
 * supabase-js v2 requires a `Relationships` key on every table, otherwise the
 * whole table type collapses to `never` and every column access errors. We
 * declare no relationships and let the explicit joins in lib/data.ts carry
 * their own casts — cheaper than hand-writing the relationship graph.
 */
type Table<Row, Insert> = {
  Row: Row
  Insert: Insert
  Update: Partial<Row>
  Relationships: []
}

export type Database = {
  public: {
    Tables: {
      lgus: Table<
        Lgu,
        Insertable<
          Lgu,
          | 'parent_id'
          | 'region'
          | 'psgc_code'
          | 'letterhead_url'
          | 'seal_url'
          | 'official_email'
          | 'registered_by'
          | 'registered_at'
          | 'logo_url'
        >
      >
      psgc_reference: {
        Row: PsgcEntry
        Insert: PsgcEntry
        Update: Partial<PsgcEntry>
        Relationships: []
      }
      egov_identities: Table<
        EgovIdentity,
        Insertable<EgovIdentity, 'suffix' | 'birthdate' | 'address' | 'email' | 'mobile' | 'updated_at'>
      >
      officers: Table<
        Officer,
        Insertable<Officer, 'egov_sub' | 'lgu_id' | 'position' | 'office' | 'role' | 'sso_email' | 'sso_birthdate'>
      >
      service_templates: Table<
        ServiceTemplate,
        Insertable<ServiceTemplate, 'description' | 'base_fields' | 'allowed_rules' | 'max_fee'>
      >
      lgu_services: Table<
        LguService,
        Insertable<
          LguService,
          | 'status'
          | 'fee_amount'
          | 'waivers'
          | 'required_docs'
          | 'eligibility'
          | 'form_fields'
          | 'doc_template_path'
          | 'source_prompt'
          | 'generated_by'
          | 'generator_model'
          | 'approval_office'
          | 'generation_confidence'
          | 'reviewed_by'
          | 'reviewed_at'
          | 'submitted_at'
          | 'published_at'
        >
      >
      validation_flags: Table<
        ValidationFlag,
        Insertable<ValidationFlag, 'severity' | 'field_path' | 'resolved' | 'resolution_note' | 'resolved_by' | 'resolved_at'>
      >
      studio_generation_cache: Table<
        StudioGenerationCache,
        Insertable<StudioGenerationCache, 'primary_error' | 'updated_at'>
      >
      requests: Table<
        ServiceRequest,
        Insertable<
          ServiceRequest,
          | 'citizen_sub'
          | 'citizen_name'
          | 'citizen_mobile'
          | 'everify_payload'
          | 'liveness_session'
          | 'liveness_passed'
          | 'form_data'
          | 'status'
          | 'fee_due'
          | 'fee_status'
          | 'waiver_applied'
          | 'payment_ref'
          | 'payment_uuid'
          | 'payment_url'
          | 'payment_txnid'
          | 'payment_source'
          | 'payment_checked_at'
          | 'uploaded_docs'
          | 'liveness_score'
          | 'everify_reference'
          | 'approved_by'
          | 'approved_at'
          | 'rejected_by'
          | 'rejected_at'
          | 'rejection_note'
          | 'issuance_status'
          | 'issuance_attempts'
          | 'issuance_started_at'
          | 'issuance_error'
          | 'control_number'
          | 'pdf_path'
          | 'doc_hash'
          | 'chain_tx'
          | 'chain_block_number'
          | 'chain_anchored_at'
          | 'chain_source'
          | 'sms_status'
          | 'sms_source'
          | 'sms_message_id'
          | 'sms_sent_at'
          | 'sms_error'
          | 'issued_at'
        >
      >
      request_events: Table<RequestEvent, Insertable<RequestEvent, 'payload'>>
      lgu_control_sequences: {
        Row: { lgu_id: string; year: number; last_value: number; updated_at: string }
        Insert: { lgu_id: string; year: number; last_value?: number; updated_at?: string }
        Update: { last_value?: number; updated_at?: string }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      save_generated_service: {
        Args: { p_lgu_id: string; p_template_code: string; p_service: Record<string, unknown>; p_flags: Record<string, unknown>[]; p_source_prompt: string | null; p_generated_by: string; p_generator_model: string }
        Returns: { service_id: string; status: ServiceStatus }[]
      }
      publish_reviewed_service: {
        Args: { p_service_id: string; p_reviewer: string }
        Returns: ServiceStatus
      }
      claim_request_approval: {
        Args: { p_request_id: string; p_officer_sub: string }
        Returns: { claimed: boolean; reason: string; sequence_value: number | null }[]
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
